### ISSUE TITLE
DefaultStorage Performance Optimization: reduce/reuse Salsa traces

### ISSUE THREAD

**Issue by rai-nhdaly** [RelationalAI-oss/Salsa.jl#20]
(We already recycle 😛)

Two separate, but related, potential performance optimizations:

https://github.com/RelationalAI-oss/Salsa.jl/blob/705f61017439290bc811e496f0abf1978ac66799/src/default_storage.jl#L182-L193

https://github.com/RelationalAI-oss/Salsa.jl/blob/705f61017439290bc811e496f0abf1978ac66799/src/default_storage.jl#L221-L229

**Comment by NHDaly** [comment]
Fixed in https://github.com/RelationalAI-oss/Salsa.jl/pull/27
